// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


describe('Reddit Login', function() {
this.timeout(30000)
let driver
let vars

beforeEach(async function() {
  driver = await new Builder().forBrowser('chrome').build()
  vars = {}
})
afterEach(async function() {
  await driver.quit();
})
  it('Reddit Login', async function() {
    await driver.get("https://reddit.com")
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.wait(until.elementLocated(By.css("#login-button > .flex > .flex")), 200)
    await driver.findElement(By.css("#login-button > .flex > .flex")).click()
    await driver.findElement(By.id("login-username")).click()
    await driver.wait(until.elementIsEnabled(await driver.findElement(By.id("login-username"))), 200)
await driver.sleep(1000)
{
  const element = await driver.findElement(By.id("login-username"))
  await driver.actions({ bridge: true}).doubleClick(element).perform()
}
await driver.findElement(By.id("login-username")).sendKeys("bigbootyrob")
await driver.findElement(By.id("login-password")).click()
await driver.findElement(By.id("login-password")).sendKeys("1893Apple")
await driver.findElement(By.css(".login > .flex > .flex")).click()
await driver.findElement(By.css(".login")).click()
  })
})
